### ISSUE TITLE
1. View entry

### ISSUE THREAD

**Issue by Nicolevm797** [Hector-SaTe/year_planner#1]
1. **delete** "selected days" and icon. 
  "68 days" must reflect the current division status in 3 colors: 
       **Green:** All divided
       **Yellow:** a few divided
       **Red:** None divided

2. Divider need to be **#CBCBCB** or **Grey - 01**

3. The total width of teams needs to be the same width as the calendar, with a 22px separation between teams. 
    The colours need to be inverted. 
     **In view mode:** the identification number of teams needs to be on colour and the day 
     number on white background. 
     **In Edit mode:** this will be inverted if it's selected to modify the days, with the T**oggle button animation**. 

4. Space between numbers on the calendar needs to be less, **as 22 px**
   And text colour is black and not white on the circle

[Issues_1](https://user-images.githubusercontent.com/123302589/216273667-c8e47a67-7985-4670-b046-2d50ccc43b98.jpg)

**Comment by Hector-SaTe** [comment]
Ok, this issue has been solved in version 2.1.0 build 5.
